services:
  postgres:
    container_name: postgres
    image: postgres
    networks:
      - tarkib
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file: .env  
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - tarkib
    ports:
      - "6379:6379"
    env_file: .env  
    volumes:
      - redis-data:/data

  minio:
    image: docker.io/bitnami/minio:2022
    networks:
      - tarkib
    ports:
      - '9000:9000'
      - '9001:9001'
    env_file: .env
    volumes:
      - 'minio-data:/data'

  app:
    build: .
    container_name: app
    networks:
      - tarkib
    image: app
    ports:
      - 8080:8080
    env_file: .env  
    depends_on:
      - postgres

networks:
  tarkib:

volumes:
  pg-data:
  redis-data:
  minio-data:
