app:
  name: 'tarkib.uz'
  version: '1.0.0'

http:
  port: '8080'

logger:
  log_level: 'debug'
  rollbar_env: 'tarkib.uz'

postgres:
  pool_max: 2

redis:
  redis_host: localhost
  redis_port: 6379
  redis_password: ''
  redis_db: 0


casbin:
  config_file_path: './config/auth.conf'
  csv_file_path: './config/auth.csv'
  signing_key: 'dfhdghkglioe'
  access_token_timeout: 604800
