basePath: /v1
definitions:
  models.ForgotPasswordRequest:
    properties:
      phone_number:
        type: string
    required:
    - phone_number
    type: object
  models.RegisterUser:
    properties:
      avatar:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      nickname:
        type: string
      password:
        type: string
      phone_number:
        type: string
    type: object
  models.ResetPasswordRequest:
    properties:
      code:
        type: string
      new_password:
        type: string
      phone_number:
        type: string
    required:
    - code
    - new_password
    - phone_number
    type: object
  models.ResetPasswordResponse:
    properties:
      message:
        type: string
    type: object
  models.VerifyUser:
    properties:
      code:
        type: string
      phoneNumber:
        type: string
    type: object
  models.VerifyUserResponse:
    properties:
      accessToken:
        type: string
      avatar:
        type: string
      firstName:
        type: string
      id:
        type: string
      lastName:
        type: string
      nickName:
        type: string
      password:
        type: string
      phoneNumber:
        type: string
    type: object
  v1.response:
    properties:
      error:
        example: message
        type: string
    type: object
info:
  contact: {}
  description: tarkib.uz
  title: tarkib.uz back-end
  version: "1.0"
paths:
  /auth/forgot:
    post:
      consumes:
      - application/json
      description: Initiates the password reset process by sending a reset code to
        the user's phone number.
      operationId: forgot-password
      parameters:
      - description: Phone number
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.ForgotPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Forgot Password
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Registers a new user
      operationId: register-user
      parameters:
      - description: User credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.RegisterUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.RegisterUser'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Register
      tags:
      - auth
  /auth/reset:
    post:
      consumes:
      - application/json
      description: Resets the user's password using the provided reset code and new
        password.
      operationId: reset-password
      parameters:
      - description: Phone number, reset code, and new password
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.ResetPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResetPasswordResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Reset Password
      tags:
      - auth
  /auth/verify:
    post:
      consumes:
      - application/json
      description: After register, user must be verified.
      operationId: verify-user
      parameters:
      - description: One time code and phone number
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.VerifyUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.VerifyUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Verify
      tags:
      - auth
swagger: "2.0"
